x-service-resource: &service-resource
  limits:
    cpus: '1'
    memory: 512M
  reservations:
    cpus: '1'
    memory: 512M

x-load-resource: &load-resource
  limits:
    cpus: '2'
    memory: 2G
  reservations:
    cpus: '2'
    memory: 2G

x-collector-resource: &collector-resource
  limits:
    cpus: '1'
    memory: 1G
  reservations:
    cpus: '1'
    memory: 1G

services:
  swo_ruby_apm_on:
    image: swo_ruby_apm_benchmark:latest
    build:
      context: ./benchmark
      dockerfile: Dockerfile
    container_name: swo_ruby_apm_benchmark_on-1
    restart: "no"
    ports:
      - 8002:8002
    environment:
      - SW_APM_COLLECTOR=${SW_APM_COLLECTOR_STG}
      - SW_APM_SERVICE_KEY=${AGENT_TOKEN_STG}
    volumes:
      - ./java-collector/server-grpc.crt:/var/app/learn-rails/server-grpc.crt
    deploy:
      resources: *service-resource

  swo_ruby_apm_otlp_on:
    image: swo_ruby_apm_benchmark:latest
    build:
      context: ./benchmark
      dockerfile: Dockerfile
    container_name: swo_ruby_apm_benchmark_otlp_on-1
    restart: "no"
    ports:
      - 8004:8002
    environment:
      - OTEL_EXPORTER_OTLP_METRICS_ENDPOINT=${OTEL_EXPORTER_OTLP_METRICS_ENDPOINT_STG}
      - OTEL_EXPORTER_OTLP_METRICS_HEADERS=${OTEL_EXPORTER_OTLP_METRICS_HEADERS_STG}
      - OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=${OTEL_EXPORTER_OTLP_TRACES_ENDPOINT_STG}
      - OTEL_EXPORTER_OTLP_TRACES_HEADERS=${OTEL_EXPORTER_OTLP_TRACES_HEADERS_STG}
      - OTEL_SERVICE_NAME=${OTEL_SERVICE_NAME}
      - SW_APM_REPORTER=file
      - OTLP_MODE_ON=true
    volumes:
      - ./java-collector/server-grpc.crt:/var/app/learn-rails/server-grpc.crt
    deploy:
      resources: *service-resource

  swo_ruby_apm_off:
    image: swo_ruby_apm_benchmark:latest
    build:
      context: ./benchmark
      dockerfile: Dockerfile
    container_name: swo_ruby_apm_benchmark_off-2
    restart: "no"
    ports:
      - 8003:8002
    environment:
      - SW_APM_COLLECTOR=${SW_APM_COLLECTOR_STG}
      - SW_APM_SERVICE_KEY=${AGENT_TOKEN_STG}
      - SW_APM_ENABLED=false
    volumes:
      - ./java-collector/server-grpc.crt:/var/app/learn-rails/server-grpc.crt
    deploy:
      resources: *service-resource

  # python container that can run locust endless
  locust_app_holder:
    image: locust_app_holder:latest
    build:
      context: ./locust-holder
      dockerfile: Dockerfile
    container_name: locust-app-holder
    # command: locust --headless -u 1 --host http://0.0.0.0:8002 --processes 4
    environment:
      - API_TOKEN=${API_TOKEN}
      - CUSTOM_METRICS_NAME=${CUSTOM_METRICS_NAME}
      - LOCUST_WAIT_TIME_L=30
      - LOCUST_WAIT_TIME_H=60
      - METRICS_ATTRIBUTE_NAME=xuan-test
    depends_on:
      - swo_ruby_apm_on
      - swo_ruby_apm_otlp_on
      - swo_ruby_apm_off
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      resources: *load-resource
